// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjY-jmrZlKO10_S5XrB3ZUaT5wY_sRw7A',
    appId: '1:217875645995:web:371ba58e56f9a1e66d8c6e',
    messagingSenderId: '217875645995',
    projectId: 'meal-recipes-app-ee087',
    authDomain: 'meal-recipes-app-ee087.firebaseapp.com',
    storageBucket: 'meal-recipes-app-ee087.appspot.com',
    measurementId: 'G-QFHD3X4Y6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU9BgQNv7JI4rf1UeRwtr7Glbsd_ed3UQ',
    appId: '1:217875645995:android:51ca164cd98d7dbb6d8c6e',
    messagingSenderId: '217875645995',
    projectId: 'meal-recipes-app-ee087',
    storageBucket: 'meal-recipes-app-ee087.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBehHa4jDLUvT0t_zszJ4Jd_63zSjF2HqE',
    appId: '1:217875645995:ios:6f7f7da8240a9e8c6d8c6e',
    messagingSenderId: '217875645995',
    projectId: 'meal-recipes-app-ee087',
    storageBucket: 'meal-recipes-app-ee087.appspot.com',
    androidClientId: '217875645995-v6vre2dnckermo92smc3ab4dp4mtivdj.apps.googleusercontent.com',
    iosClientId: '217875645995-c4pbb2s5klqsong0310cuacbprjfpsvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.meals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBehHa4jDLUvT0t_zszJ4Jd_63zSjF2HqE',
    appId: '1:217875645995:ios:6f7f7da8240a9e8c6d8c6e',
    messagingSenderId: '217875645995',
    projectId: 'meal-recipes-app-ee087',
    storageBucket: 'meal-recipes-app-ee087.appspot.com',
    androidClientId: '217875645995-v6vre2dnckermo92smc3ab4dp4mtivdj.apps.googleusercontent.com',
    iosClientId: '217875645995-c4pbb2s5klqsong0310cuacbprjfpsvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.meals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjY-jmrZlKO10_S5XrB3ZUaT5wY_sRw7A',
    appId: '1:217875645995:web:cfe6549d81f336c46d8c6e',
    messagingSenderId: '217875645995',
    projectId: 'meal-recipes-app-ee087',
    authDomain: 'meal-recipes-app-ee087.firebaseapp.com',
    storageBucket: 'meal-recipes-app-ee087.appspot.com',
    measurementId: 'G-3MXQF2VDCZ',
  );
}
